// Copyright 2026 jegly. Licensed under the GNU General Public License v2.0 or later.

/**
 * @fileoverview
 * 'settings-iris-hardening-page': Iris's own privacy and hardening switches,
 * grouped by topic, on one sub-page of Privacy and security
 * (patches/apply-iris-hardening-page.sh). The template is generated by that
 * script from the toggles the other Iris patches add.
 */

import '/shared/settings/prefs/prefs.js';
import '../controls/settings_toggle_button.js';
import '../settings_page/settings_subpage.js';
import '../settings_shared.css.js';

import {PrefsMixin} from '/shared/settings/prefs/prefs_mixin.js';
import {I18nMixin} from 'chrome://resources/cr_elements/i18n_mixin.js';
import {PolymerElement} from 'chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js';

import {SettingsViewMixin} from '../settings_page/settings_view_mixin.js';

import {getTemplate} from './iris_hardening_page.html.js';

const SettingsIrisHardeningPageElementBase =
    SettingsViewMixin(I18nMixin(PrefsMixin(PolymerElement)));

export class SettingsIrisHardeningPageElement extends
    SettingsIrisHardeningPageElementBase {
  static get is() {
    return 'settings-iris-hardening-page';
  }

  static get template() {
    return getTemplate();
  }

  // SettingsViewMixin implementation.
  override focusBackButton() {
    this.shadowRoot!.querySelector('settings-subpage')!.focusBackButton();
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'settings-iris-hardening-page': SettingsIrisHardeningPageElement;
  }
}

customElements.define(
    SettingsIrisHardeningPageElement.is, SettingsIrisHardeningPageElement);
