// Copyright 2026 jegly. Licensed under the GNU General Public License v2.0 or later.
// GENERATED by branding/gen_palettes_android.py from patches/src/ui/color/iris_palettes.h - do not edit.

package org.chromium.chrome.browser.iris;

import org.chromium.base.ContextUtils;
import org.chromium.build.annotations.NullMarked;
import org.chromium.chrome.R;

/**
 * Iris colour palettes on Android (59, same as desktop). The chosen palette is stored as a plain app
 * preference ({@link #PREF}, index; default 0 = Catppuccin Mocha) and applied as a theme overlay when its
 * light/dark kind matches the current mode (choosing a palette also switches the mode).
 */
@NullMarked
public final class IrisPalettes {
    public static final String PREF = "iris_palette";

    public static final String[] NAMES = {
        "Catppuccin Mocha",
        "Catppuccin Macchiato",
        "Catppuccin Frappé",
        "Catppuccin Latte",
        "Dracula",
        "Vintage Light",
        "Neon Tessera",
        "Adventure Time",
        "Borland",
        "Commodore 64",
        "Fairy Floss Dark",
        "Flat",
        "Gogh — Starry Night",
        "Grass",
        "Gruvbox Material",
        "Homebrew",
        "Ocean",
        "Kokuban",
        "Mono Cyan",
        "Aci",
        "Afterglow",
        "Argonaut",
        "Aura",
        "Ayu Mirage",
        "Belafonte",
        "Birds Of Paradise",
        "Blazer",
        "Brogrammer",
        "Chalkboard",
        "Espresso Libre",
        "Everforest",
        "Flatland",
        "Github",
        "Ibm3270",
        "Ic Green Ppl",
        "Kanagawa",
        "Material",
        "Mona Lisa",
        "Monokai Pro",
        "Omni",
        "Paraiso Dark",
        "Pixiefloss",
        "Powershell",
        "Relaxed",
        "Sea Shells",
        "Solarized",
        "Spacedust",
        "Spring",
        "Twilight",
        "Urple",
        "XTerm",
        "Nord",
        "Bim",
        "Cobalt Neon",
        "Homebrew Ocean",
        "Mono Amber",
        "Mono Red",
        "Synthwave",
        "Fairy Floss"
    };

    public static final boolean[] DARK = {true, true, true, false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true};

    private static final int[] STYLES = {
        R.style.ThemeOverlay_Iris_Palette0,
        R.style.ThemeOverlay_Iris_Palette1,
        R.style.ThemeOverlay_Iris_Palette2,
        R.style.ThemeOverlay_Iris_Palette3,
        R.style.ThemeOverlay_Iris_Palette4,
        R.style.ThemeOverlay_Iris_Palette5,
        R.style.ThemeOverlay_Iris_Palette6,
        R.style.ThemeOverlay_Iris_Palette7,
        R.style.ThemeOverlay_Iris_Palette8,
        R.style.ThemeOverlay_Iris_Palette9,
        R.style.ThemeOverlay_Iris_Palette10,
        R.style.ThemeOverlay_Iris_Palette11,
        R.style.ThemeOverlay_Iris_Palette12,
        R.style.ThemeOverlay_Iris_Palette13,
        R.style.ThemeOverlay_Iris_Palette14,
        R.style.ThemeOverlay_Iris_Palette15,
        R.style.ThemeOverlay_Iris_Palette16,
        R.style.ThemeOverlay_Iris_Palette17,
        R.style.ThemeOverlay_Iris_Palette18,
        R.style.ThemeOverlay_Iris_Palette19,
        R.style.ThemeOverlay_Iris_Palette20,
        R.style.ThemeOverlay_Iris_Palette21,
        R.style.ThemeOverlay_Iris_Palette22,
        R.style.ThemeOverlay_Iris_Palette23,
        R.style.ThemeOverlay_Iris_Palette24,
        R.style.ThemeOverlay_Iris_Palette25,
        R.style.ThemeOverlay_Iris_Palette26,
        R.style.ThemeOverlay_Iris_Palette27,
        R.style.ThemeOverlay_Iris_Palette28,
        R.style.ThemeOverlay_Iris_Palette29,
        R.style.ThemeOverlay_Iris_Palette30,
        R.style.ThemeOverlay_Iris_Palette31,
        R.style.ThemeOverlay_Iris_Palette32,
        R.style.ThemeOverlay_Iris_Palette33,
        R.style.ThemeOverlay_Iris_Palette34,
        R.style.ThemeOverlay_Iris_Palette35,
        R.style.ThemeOverlay_Iris_Palette36,
        R.style.ThemeOverlay_Iris_Palette37,
        R.style.ThemeOverlay_Iris_Palette38,
        R.style.ThemeOverlay_Iris_Palette39,
        R.style.ThemeOverlay_Iris_Palette40,
        R.style.ThemeOverlay_Iris_Palette41,
        R.style.ThemeOverlay_Iris_Palette42,
        R.style.ThemeOverlay_Iris_Palette43,
        R.style.ThemeOverlay_Iris_Palette44,
        R.style.ThemeOverlay_Iris_Palette45,
        R.style.ThemeOverlay_Iris_Palette46,
        R.style.ThemeOverlay_Iris_Palette47,
        R.style.ThemeOverlay_Iris_Palette48,
        R.style.ThemeOverlay_Iris_Palette49,
        R.style.ThemeOverlay_Iris_Palette50,
        R.style.ThemeOverlay_Iris_Palette51,
        R.style.ThemeOverlay_Iris_Palette52,
        R.style.ThemeOverlay_Iris_Palette53,
        R.style.ThemeOverlay_Iris_Palette54,
        R.style.ThemeOverlay_Iris_Palette55,
        R.style.ThemeOverlay_Iris_Palette56,
        R.style.ThemeOverlay_Iris_Palette57,
        R.style.ThemeOverlay_Iris_Palette58
    };

    private IrisPalettes() {}

    /** Index of the chosen palette (0 = Catppuccin Mocha). */
    public static int getSelected() {
        int i = ContextUtils.getAppSharedPreferences().getInt(PREF, 0);
        return i >= 0 && i < STYLES.length ? i : 0;
    }

    public static void setSelected(int index) {
        ContextUtils.getAppSharedPreferences().edit().putInt(PREF, index).apply();
    }

    /** The theme overlay to apply for the current mode, or 0 if the chosen palette is for the other mode. */
    public static int overlayFor(boolean nightMode) {
        int i = getSelected();
        return DARK[i] == nightMode ? STYLES[i] : 0;
    }
}
